<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NarahubungJazirahSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['id' => 1, 'gmail' => 'zibps1101@gmail.com', 'email_bps' => null, 'nama' => 'Alfredo Abdul Aziz', 'satker' => '1101', 'role' => 'PJ Satker', 'no_hp' => '81289771037', 'status' => 1],
            ['id' => 2, 'gmail' => 'timzibpsacehsingkil@gmail.com', 'email_bps' => null, 'nama' => 'Syahrul Yuanda', 'satker' => '1102', 'role' => 'PJ Satker', 'no_hp' => '82165075327', 'status' => 1],
            ['id' => 3, 'gmail' => 'subbagumum1103@gmail.com', 'email_bps' => null, 'nama' => 'Adlin', 'satker' => '1103', 'role' => 'PJ Satker', 'no_hp' => '85277603539', 'status' => 1],
            ['id' => 4, 'gmail' => '11040bps@gmail.com', 'email_bps' => null, 'nama' => 'Mustapa Kamal', 'satker' => '1104', 'role' => 'PJ Satker', 'no_hp' => '82164839831', 'status' => 1],
            ['id' => 5, 'gmail' => 'atimkabbps@gmail.com', 'email_bps' => null, 'nama' => 'Jufri', 'satker' => '1105', 'role' => 'PJ Satker', 'no_hp' => '85262224625', 'status' => 1],
            ['id' => 6, 'gmail' => 'bpsacehtengah06@gmail.com', 'email_bps' => null, 'nama' => 'Effendy', 'satker' => '1106', 'role' => 'PJ Satker', 'no_hp' => '852777777785', 'status' => 1],
            ['id' => 7, 'gmail' => 'bps.kabacehbarat@gmail.com', 'email_bps' => null, 'nama' => 'Yulia Geubrina', 'satker' => '1107', 'role' => 'PJ Satker', 'no_hp' => '81269780880', 'status' => 1],
            ['id' => 8, 'gmail' => 'bps1108.zi@gmail.com', 'email_bps' => null, 'nama' => 'Ar Razy Ridha Maulana', 'satker' => '1108', 'role' => 'PJ Satker', 'no_hp' => '8116855445', 'status' => 1],
            ['id' => 9, 'gmail' => 'bpspidie1109@gmail.com', 'email_bps' => null, 'nama' => 'Annisa Rahmawati', 'satker' => '1109', 'role' => 'PJ Satker', 'no_hp' => '85876522989', 'status' => 1],
            ['id' => 10, 'gmail' => 'bpsbireuen1@gmail.com', 'email_bps' => null, 'nama' => 'Muhammad Rian Fazli', 'satker' => '1110', 'role' => 'PJ Satker', 'no_hp' => '85260018229', 'status' => 1],
            ['id' => 11, 'gmail' => 'zibpsau@gmail.com', 'email_bps' => null, 'nama' => 'Pinky Aulia Viradina', 'satker' => '1111', 'role' => 'PJ Satker', 'no_hp' => '85705206017', 'status' => 1],
            ['id' => 12, 'gmail' => 'bps1112.zonaintegritas@gmail.com', 'email_bps' => null, 'nama' => 'Lisa Nurlyeni', 'satker' => '1112', 'role' => 'PJ Satker', 'no_hp' => '82298531916', 'status' => 1],
            ['id' => 13, 'gmail' => 'gayoluesbps@gmail.com', 'email_bps' => null, 'nama' => 'Febby Adrian', 'satker' => '1113', 'role' => 'PJ Satker', 'no_hp' => '82252840039', 'status' => 1],
            ['id' => 14, 'gmail' => 'zibps1114@gmail.com', 'email_bps' => null, 'nama' => 'Wahyu Agung Sutikno', 'satker' => '1114', 'role' => 'PJ Satker', 'no_hp' => '81376302090', 'status' => 1],
            ['id' => 15, 'gmail' => 'bpsnaganraya15@gmail.com', 'email_bps' => null, 'nama' => 'Ghifari Azka Wali', 'satker' => '1115', 'role' => 'PJ Satker', 'no_hp' => '82299428874', 'status' => 1],
            ['id' => 16, 'gmail' => 'bpsacehjaya1116@gmail.com', 'email_bps' => null, 'nama' => 'Elda Elnovita', 'satker' => '1116', 'role' => 'PJ Satker', 'no_hp' => '81360036013', 'status' => 1],
            ['id' => 17, 'gmail' => 'zibpsbm2025@gmail.com', 'email_bps' => null, 'nama' => 'Cut Meutia', 'satker' => '1117', 'role' => 'PJ Satker', 'no_hp' => '85296500382', 'status' => 1],
            ['id' => 18, 'gmail' => 'agmipurnama15@gmail.com', 'email_bps' => null, 'nama' => 'Agmi Purnama', 'satker' => '1118', 'role' => 'PJ Satker', 'no_hp' => '81261004510', 'status' => 1],
            ['id' => 19, 'gmail' => 'bpsbna1171@gmail.com', 'email_bps' => null, 'nama' => 'M. Muflik Teguh Yuli Pitoyo', 'satker' => '1171', 'role' => 'PJ Satker', 'no_hp' => '81230696065', 'status' => 1],
            ['id' => 20, 'gmail' => 'sabang1172@gmail.com', 'email_bps' => null, 'nama' => 'Muhammad Khairi Albanna S.', 'satker' => '1172', 'role' => 'PJ Satker', 'no_hp' => '81265435572', 'status' => 1],
            ['id' => 21, 'gmail' => '1173bpslangsa@gmail.com', 'email_bps' => null, 'nama' => 'Nanda Safwati', 'satker' => '1173', 'role' => 'PJ Satker', 'no_hp' => '82125889836', 'status' => 1],
            ['id' => 22, 'gmail' => 'bps1174.04@gmail.com', 'email_bps' => null, 'nama' => 'Zulkarnaini', 'satker' => '1174', 'role' => 'PJ Satker', 'no_hp' => '82363851715', 'status' => 1],
            ['id' => 23, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1101', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 24, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1101', 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 25, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1101', 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 26, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1101', 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 27, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1101', 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 28, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => '1101', 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 29, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1102', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 30, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 31, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 32, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 33, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 34, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 35, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1103', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 36, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 37, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 38, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 39, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 40, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 41, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1104', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 42, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 43, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 44, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 45, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 46, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 47, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1105', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 48, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 49, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 50, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 51, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 52, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 53, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1106', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 54, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 55, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 56, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 57, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 58, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 59, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1107', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 60, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 61, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 62, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 63, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 64, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 65, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1108', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 66, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 67, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 68, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 69, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 70, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 71, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1109', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 72, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 73, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 74, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 75, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 76, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 77, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1110', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 78, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 79, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 80, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 81, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 82, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 83, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1111', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 84, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 85, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 86, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 87, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 88, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 89, 'gmail' => 'itameriati3@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1112', 'role' => 'Evaluator Pilar 1', 'no_hp' => null, 'status' => 1],
            ['id' => 90, 'gmail' => 'nasliyahhusna0@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85261382870', 'status' => 1],
            ['id' => 91, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 92, 'gmail' => 'persediaan.bps1100@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => '81314111016', 'status' => 1],
            ['id' => 93, 'gmail' => 'dewiumar940@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85262079819', 'status' => 1],
            ['id' => 94, 'gmail' => null, 'email_bps' => null, 'nama' => 'Nyimas Eka Yunia Hasnita', 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => null, 'status' => 1],
            ['id' => 95, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1113', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 96, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 97, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 98, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 99, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 100, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 101, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1114', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 102, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 103, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 104, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 105, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 106, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 107, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1115', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 108, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 109, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 110, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 111, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 112, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 113, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1116', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 114, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 115, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 116, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 117, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 118, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 119, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1117', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 120, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 121, 'gmail' => 'novaandri22@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => null, 'status' => 1],
            ['id' => 122, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 123, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 124, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 125, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1118', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 126, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 127, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 128, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 129, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 130, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 131, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1171', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 132, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 133, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 134, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 135, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 136, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 137, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1172', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 138, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 139, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 140, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 141, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 142, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 143, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1173', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 144, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 145, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 146, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 147, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 148, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 149, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1174', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 150, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 151, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 152, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 153, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 154, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 155, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1175', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 156, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 157, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 158, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 159, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 160, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
            ['id' => 161, 'gmail' => 'alfibps@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => '1100', 'role' => 'Evaluator Pilar 1', 'no_hp' => '8126943730', 'status' => 1],
            ['id' => 162, 'gmail' => 'maulidin.tkl@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 2', 'no_hp' => '85211587757', 'status' => 1],
            ['id' => 163, 'gmail' => 'ambiyasaiful27@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 3', 'no_hp' => '85296823974', 'status' => 1],
            ['id' => 164, 'gmail' => null, 'email_bps' => null, 'nama' => 'Zukhra ', 'satker' => null, 'role' => 'Evaluator Pilar 4', 'no_hp' => null, 'status' => 1],
            ['id' => 165, 'gmail' => 'bpsaceh11514@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 5', 'no_hp' => '85260025334', 'status' => 1],
            ['id' => 166, 'gmail' => 'Reyhanoctaviandri@gmail.com', 'email_bps' => null, 'nama' => null, 'satker' => null, 'role' => 'Evaluator Pilar 6', 'no_hp' => '81368714091', 'status' => 1],
        ];

        $now = now();
        $rows = array_map(function ($r) use ($now) {
            $r['created_at'] = $now;
            $r['updated_at'] = $now;
            return $r;
        }, $rows);

        // Optional: clear table first
        // DB::table('narahubung_jazirah')->truncate();

        // Insert
        DB::table('narahubung_jazirah')->insert($rows);
    }
}
